### ISSUE TITLE
Loggin event disconect player or no send from lobbyauth to lobby

### ISSUE THREAD

**Issue by maxmar628** [leonardo-dgs/ABungeeAuth#3]
I have a network and lose many player for this insue.

Im used 1.3.1 version and some times, when player enter on server, whit premium or cracked launcher, the event for teleport players from lobbyauth to lobby are bugged and dont send players.
No error on console, but this is a huge problem!! Please fix dude

**Comment by leonardo-dgs** [comment]
Fixed in v1.4.3
